### PR TITLE
v 3.11.2

### PR DESCRIPTION
**Pull request by ReimarBauer**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [-] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by ReimarBauer** [comment]
@conda-forge-admin this is the base of python-socketio which we use in mss-feedstock for our colaboration managment. 
A new developer using vmware in our project recognized that we need a newer version, because of failing tests in our project. 

There were some bot requests not handled I want to help with maintaining this package.

**Comment by ReimarBauer** [comment]
@conda-forge-coordinator Hi there hope that is now the correct address. Can you add me as maintainer for this package?

**Comment by ReimarBauer** [comment]
HI @conda-forge/staged-recipes need help, can you merge my PR, and make me a maintainer?

**Comment by synapticarbors** [comment]
@ReimarBauer thanks for volunteering to co-maintain this feedstock

**Pull request merged**
